export default function blog() {
    return {
        "h1": "Blog 2",
        "summary": "This is a blog 2 about a lot of interesting stuff...",
        "h2": {
            "titles": ["To Start...", "To End..."],
            "paragraphs": [
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem perferendis non voluptates ratione. Voluptatum voluptate consequuntur minus numquam, quos in dolore, delectus porro non perspiciatis enim voluptatem atque voluptates expedita Reprehenderit, quisquam. Nemo quas fugit ipsa nisi atque dolore alias ad repellat in soluta eius quo libero asperiores odio nostrum, beatae dolor ullam numquam officia aliquid, quos voluptatem dicta. Necessitatibus Dolor nesciunt tempora consequatur sapiente deserunt est accusamus perspiciatis, recusanae modi, praesentium earum ad molestiae, harum sint at cum et eaque quam suscipit! Quasi mollitia amet culpa iste, eos quisquam Facere obcaecati nam nemo sequi doloremque possimus nesciunt cum amet numquam beatae et accusantium, dicta, dolorem iure labore temporibus modi delectus alias molestiae. Harum ullam odit esse, pariatur quae eligendi Iusto, aspernatur illo aperiam doloremque nobis, assumenda iure eos numquam vero sint commodi saepe expedita odio fugit blanditiis, voluptate officiis corrupti voluptas voluptatem. Nostrum animi consectetur aspernatur, corporis maxime quaerat",
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Autem perferendis non voluptates ratione. Voluptatum voluptate consequuntur minus numquam, quos in dolore, delectus porro non perspiciatis enim voluptatem atque voluptates expedita Reprehenderit, quisquam. Nemo quas fugit ipsa nisi atque dolore alias ad repellat in soluta eius quo libero asperiores odio nostrum, beatae dolor ullam numquam officia aliquid, quos voluptatem dicta. Necessitatibus Dolor nesciunt tempora consequatur sapiente deserunt est accusamus perspiciatis, recusanae modi, praesentium earum ad molestiae, harum sint at cum et eaque quam suscipit! Quasi mollitia amet culpa iste, eos quisquam Facere obcaecati nam nemo sequi doloremque possimus nesciunt cum amet numquam beatae et accusantium, dicta, dolorem iure labore temporibus modi delectus alias molestiae. Harum ullam odit esse, pariatur quae eligendi Iusto, aspernatur illo aperiam doloremque nobis, assumenda iure eos numquam vero sint commodi saepe expedita odio fugit blanditiis, voluptate officiis corrupti voluptas voluptatem. Nostrum animi consectetur aspernatur, corporis maxime quaerat"
            ]
        }
    }
}